[workspace]
channels = ["conda-forge"]
name = "fiji-macro"
platforms = ["win-64", "osx-arm64"]
version = "0.1.0"

[tasks]
download-data = "curl -L https://zenodo.org/api/records/18020241/files-archive --output data/Drosophila-CP --create-dirs"

[dependencies]
