[workspace]
channels = ["conda-forge"]
name = "fiji-macro"
platforms = ["win-64", "osx-arm64"]
version = "0.1.0"

[tasks]
download-data = """
mkdir -p data &&
curl -L https://zenodo.org/api/records/18020241/files-archive \
  --output data/Drosophila-CP.zip &&
unzip -o data/Drosophila-CP.zip -d data/Drosophila-CP
"""
[dependencies]
